In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn import svm

from tensorflow.keras.utils import to_categorical
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import Sequential

%matplotlib inline

In [3]:
def comprehension(vetor, func):
  array = list()

  for i in range(len(vetor)):
    if func == np.mean or func == np.reshape:
      array.append(func(vetor[i], -1))
    else:
      array.append(func(vetor[i]))

  return np.array(array)

In [4]:
df = pd.read_csv("faces.csv") 
df.head()

Unnamed: 0         0         1         2         3         4         5  \
0           0  0.624656 -0.447745  0.624376  0.168215 -1.183529  1.161336   
1           1  0.921183 -0.228285  1.023043 -0.362588 -0.759581  0.905878   
2           2 -0.037906 -0.927606  0.960223  0.052220 -1.199638  0.768999   
3           3  0.677615 -0.018155  0.723042 -0.119465 -1.317164  1.009346   
4           4  0.841432 -0.305600  0.955496 -0.508191 -0.417205  1.673414   

          6         7         8  ...       119       120       121       122  \
0  1.180575 -1.458736  0.925821  ... -1.062742  0.596569  0.682379  0.292868   
1  1.626263 -1.420151  1.193603  ... -1.375485  0.683259  0.827911 -0.167854   
2  1.396971 -0.688852  0.781067  ... -1.764692  0.959367  0.720395 -0.322032   
3  1.103884 -1.569089  0.324309  ... -0.621289  0.506900  0.757364  0.247419   
4  0.809553 -1.041964  1.069607  ... -0.451649  0.114553  0.892378  0.363496   

        123       124       125       126       127     target  
0  0.409854  1.634237  0.249691 -0.189478 -1.783221  glauciane  
1  0.260004  1.484647  0.228390 -0.471342 -1.681182  glauciane  
2  0.306745  1.598800 -0.141811 -0.795695 -1.841082  glauciane  
3  0.131484  1.497606  0.284347 -0.406723 -2.066759  glauciane  
4  0.414226  2.106771 -0.339435 -0.562916 -2.133557  glauciane  

[5 rows x 130 columns]

In [5]:
X = np.array(df.drop(["Unnamed: 0","target"], axis=1))
X.shape

(484, 128)

In [6]:
y = np.array(df.target)
y.shape

(484,)

In [7]:
trainX, trainY = shuffle(X, y, random_state = 0) # misturando tudo 

## TRATANDO AS LABELS

In [8]:
out_encoder = LabelEncoder() # enumerando as saidas
out_encoder.fit(trainY)

LabelEncoder()

In [9]:
trainY = out_encoder.transform(trainY)
# trainY

## IMPORTANDO DADOS DE VALIDAÇÃO 

In [10]:
df_val = pd.read_csv("faces_validation.csv")
df_val = df_val.drop('Unnamed: 0', axis=1)
df_val.tail()

0         1         2         3         4         5         6  \
179 -0.463136  2.031797 -0.828680  0.677253 -0.438864 -1.767040 -1.271514   
180 -0.553705  1.613878 -0.417959  0.387931  0.131402 -1.294715 -1.165642   
181 -0.447034  2.120559 -1.170795  0.405479 -0.547222 -1.574009 -1.625558   
182 -0.676332  1.565943 -0.908553  0.160335 -0.093269 -1.125900 -0.745321   
183 -0.274737  1.392665 -1.028112  0.387853 -0.309734 -1.539772 -1.086364   

            7         8         9  ...       119       120       121  \
179 -1.461169  0.322037  0.581745  ...  1.388556  1.173924 -0.699268   
180 -1.541113  0.309136  0.132032  ...  1.045077  1.558633 -0.642279   
181 -0.939384 -0.007186  0.310999  ...  0.997773  1.265311 -0.490962   
182 -1.402514  0.278516  0.107065  ...  1.363476  1.532303  0.017134   
183 -1.284094  0.407558  0.555285  ...  0.800906  1.066285 -0.073062   

          122       123       124       125       126       127     target  
179 -1.318101 -0.913755  0.526818  0.256470  0.994789  0.812019  steferson  
180 -1.194365 -1.038592  0.515083  0.201941  0.076190  0.950706  steferson  
181 -1.330633 -0.533949  0.651528  0.539643  0.632580  0.760968  steferson  
182 -1.364406 -0.830635  0.263987  0.800664  0.107907  0.803421  steferson  
183 -1.016491 -0.856045  0.317577  0.654202 -0.076276  0.688481  steferson  

[5 rows x 129 columns]

## PREPARANDO VARIAVEIS DE VALIDAÇÃO 

In [11]:
valX = np.array(df_val.drop("target", axis = 1))
valY = np.array(df_val.target)

In [12]:
out_encoder.fit(valY)

LabelEncoder()

In [13]:
valY = out_encoder.transform(valY)
# valY

# AVALIANDO ALGORITMOS

### KNN

In [18]:
knn = KNeighborsClassifier(n_neighbors = 1)

In [19]:
knn.fit(trainX, trainY) # treinando algoritmo com os dados de treino

KNeighborsClassifier(n_neighbors=1)

In [20]:
yhat_train_knn = knn.predict(trainX) # predizendo os resultados dos dados de treino
yhat_val_knn = knn.predict(valX) # predizendo os resultados dos dados de validação
yhat_train_knn

In [22]:
# Imprimindo a matriz confusa
print("Matriz Confusa: ")
print(confusion_matrix(valY, yhat_val_knn), "\n") 

# Imprimindo o relatório de classificação
print("Relatório de classificação: \n", classification_report(valY, yhat_val_knn)) 

# Imprimindo o quão acurado foi o modelo
print('Acurácia do modelo: ' , accuracy_score(valY, yhat_val_knn))

Matriz Confusa: 
[[72  0  0]
 [ 0 76  0]
 [ 0  0 36]] 

Relatório de classificação: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        72
           1       1.00      1.00      1.00        76
           2       1.00      1.00      1.00        36

    accuracy                           1.00       184
   macro avg       1.00      1.00      1.00       184
weighted avg       1.00      1.00      1.00       184

Acurácia do modelo:  1.0


### SVM

In [24]:
svm = svm.SVC()
svm.fit(trainX,trainY)

SVC()

In [25]:
yhat_train_svm = svm.predict(trainX)
yhat_val_svm = svm.predict(valX)

In [26]:
# Imprimindo a matriz confusa
print("Matriz Confusa: ")
print(confusion_matrix(valY, yhat_val_svm), "\n") 

# Imprimindo o relatório de classificação
print("Relatório de classificação: \n", classification_report(valY, yhat_val_svm)) 

# Imprimindo o quão acurado foi o modelo
print('Acurácia do modelo: ' , accuracy_score(valY, yhat_val_svm))

Matriz Confusa: 
[[72  0  0]
 [ 0 76  0]
 [ 0  0 36]] 

Relatório de classificação: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        72
           1       1.00      1.00      1.00        76
           2       1.00      1.00      1.00        36

    accuracy                           1.00       184
   macro avg       1.00      1.00      1.00       184
weighted avg       1.00      1.00      1.00       184

Acurácia do modelo:  1.0


### KERAS

In [27]:
trainY = to_categorical(trainY)


In [28]:
valY = to_categorical(valY)
# valY

In [29]:
model = models.Sequential()
model.add(layers.Dense(64, activation = 'relu', input_shape = (128,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(3, activation="softmax"))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                8256      
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense_1 (Dense)             (None, 3)                 195       
                                                                 
Total params: 8,451
Trainable params: 8,451
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(optimizer="adam", loss= "categorical_crossentropy", metrics=['accuracy'])

In [33]:
model.fit(trainX, trainY, epochs=100, batch_size = 8)

Epoch 1/100


ValueError: in user code:

    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 810, in train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/losses.py", line 1665, in categorical_crossentropy
        y_true, y_pred, from_logits=from_logits, axis=axis)
    File "/home/vitor/anaconda3/lib/python3.7/site-packages/keras/backend.py", line 4994, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 1) and (None, 3) are incompatible


In [32]:
yhat_val_keras = model.predict(valX)
yhat_train_keras = model.predict(trainX)
yhat_train_keras = comprehension(yhat_train_keras, np.argmax)
yhat_val_keras = comprehension(yhat_val_keras, np.argmax)
trainY = np.argmax(trainY, axis = 1)
# yhat_train_keras
# trainY


In [ ]:
valY = np.argmax(valY, axis = 1)